#!/usr/bin/env bash

unset OS_USERNAME OS_TENANT_NAME OS_PASSWORD OS_AUTH_URL
export SERVICE_TOKEN=$(cat /root/ks_admin_token)
export SERVICE_ENDPOINT=http://server12-a.example.com:35357/v2.0
export PS1='[\u@\h \W(keystone_token)]\$ '
