#!/usr/bin/env bash

unset SERVICE_TOKEN SERVICE_ENDPOINT
export OS_USERNAME=admin
export OS_TENANT_NAME=admin
export OS_PASSWORD=redhat
export OS_AUTH_URL=http://server12-a.example.com:35357/v2.0/
export PS1='[\u@\h \W(keystone_admin)]\$ '
