#!/usr/bin/env bash

unset SERVICE_TOKEN SERVICE_ENDPOINT
export OS_USERNAME=myuser
export OS_TENANT_NAME=myopenstack
export OS_PASSWORD=redhat
export OS_AUTH_URL=http://server12-a.example.com:5000/v2.0/
export PS1='[\u@\h \W(keystone_myuser)]\$ '
